# Generated by Django 2.1.7 on 2019-04-01 04:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, verbose_name='姓名')),
                ('password', models.CharField(max_length=10, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.User')),
                ('token', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
