# Generated by Django 2.1.7 on 2019-04-01 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_carer_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='carer',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Hospital'),
            preserve_default=False,
        ),
    ]
