# Generated by Django 2.1.7 on 2019-04-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='carer',
            name='num_family',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carer',
            name='num_hospital',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carer',
            name='num_patient',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carer',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='side',
            field=models.IntegerField(default=0, verbose_name='方'),
        ),
    ]
